apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-demo
  name: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: nrt.ocir.io/nrmnnnuwlffe/nrt-cn-handson-<your_name>/nginx-demo:1.0
        name: nginx-demo
        resources: {}
status: {}
